#pragma once

#define	MAIN_WINDOW_CNAME _T("QR_CODER_WND_CLASS")
#define WINDOW_PROPERTY_QRDRAWER _T("QRDC")
#define CMD_STRING_OPTION _T("--str")
#define CMD_SHAPE_OPTION _T("--shape")
#define CMD_SIZE_OPTION _T("--size")
#define DEFAULT_MODULE_SIZE 10
#define DEFAULT_FOREGROUND_COLOR RGB(0, 0, 0)
#define DEFAULT_BACKGROUND_COLOR RGB(255, 255, 255)
#define DEFAULT_MODULE_SHAPE	SQUARE
#define DIRECT_REDRAW	false